### ISSUE TITLE
Error/warn, it doesn't show any history for any of the players. 

### ISSUE THREAD

**Issue by Getblock** [ChestShop-authors/ChestShopNotifier#34] opened 2019-12-21 08:15 UTC
[12:22:04] [Craft Scheduler Thread - 20/WARN]: [ChestShopNotifier] Plugin ChestShopNotifier v1.3.0-SNAPSHOT (build #37) generated an exception while executing task 24064
java.lang.IllegalStateException: CurrencyFormatEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-237]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:442) ~[?:?]
	at com.Acrobot.ChestShop.Economy.Economy.formatBalance(Economy.java:71) ~[?:?]
	at com.Acrobot.ChestShop.Economy.Economy.formatBalance(Economy.java:81) ~[?:?]
	at com.wfector.command.History.showResults(History.java:121) ~[?:?]
	at com.wfector.command.History.run(History.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]

**Comment by Phoenix616** [comment] 2019-12-21 13:32
You are not running the latest build (39), that one should have this issue fixed.

**Comment by Phoenix616** [comment] 2020-01-04 02:47
Duplicate of #30

**Closed** 2020-01-04 02:47 UTC
Labels: invalid
