### ISSUE TITLE
EventHandler method warning console

### ISSUE THREAD

**Issue by FITFC** [ChestShop-authors/ChestShopNotifier#62] opened 2022-03-16 03:59 UTC
CSN Version: v1.3.3 (build 51)
Server base: git-Purpur-1586 (MC: 1.18.2)

[00:57:35 WARN]: @EventHandler method com.wfector.notifier.ChestShopNotifier#onChestShopTransaction returns non-void type boolean. This is unsupported behavior and will no longer work in a future version of Paper. This should be reported to the developers of ChestShopNotifier v1.3.3 (build 51) (BetaBlaze,Phoenix616,FrankHeijden)

**Comment by Phoenix616** [comment] 2022-03-16 09:25
Duplicate of #59 and already fixed. Please update to the latest dev builds.

**Closed** 2022-03-16 09:25 UTC
