### ISSUE TITLE
exception while executing task 48631

### ISSUE THREAD

**Issue by NullCase** [ChestShop-authors/ChestShopNotifier#32] opened 2019-07-27 13:52 UTC
Hi Phoenix616! We've finally updated to 1.14. Found this error message and wanted to share it with you.

Also, since i've got the excuse to say something it looks like CheaperPhysicsEvent works in 1.14 but it seems like you'd know that. It's good news and means I'll get to throw some money your way in a few months.

```
27.07 09:52:47 [Server] INFO Dioswilson issued server command: /csn history
27.07 09:52:47 [Server] WARN [ChestShopNotifier] Plugin ChestShopNotifier v1.3.0-SNAPSHOT (build #36) generated an exception while executing task 48631
27.07 09:52:47 [Server] INFO java.lang.IllegalStateException: CurrencyFormatEvent may only be triggered synchronously.
27.07 09:52:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-148]
27.07 09:52:47 [Server] INFO at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:442) ~[?:?]
27.07 09:52:47 [Server] INFO at com.Acrobot.ChestShop.Economy.Economy.formatBalance(Economy.java:71) ~[?:?]
27.07 09:52:47 [Server] INFO at com.Acrobot.ChestShop.Economy.Economy.formatBalance(Economy.java:81) ~[?:?]
27.07 09:52:47 [Server] INFO at com.wfector.command.History.showResults(History.java:121) ~[?:?]
27.07 09:52:47 [Server] INFO at com.wfector.command.History.run(History.java:46) ~[?:?]
27.07 09:52:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-148]
27.07 09:52:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-148]
27.07 09:52:47 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-148]
27.07 09:52:47 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
27.07 09:52:47 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
27.07 09:52:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Phoenix616** [comment] 2019-07-27 13:55
Duplicate of #30 and already fixed in build 39 :)

**Closed by Phoenix616** 2019-07-27 13:55 UTC
Labels: duplicate
